NATIONALITIES = [
    {'code': 'AFG', 'cn': '阿富汗', 'en': 'Afghanistan'},
    {'code': 'ALB', 'cn': '阿尔巴尼亚', 'en': 'Albania'},
    {'code': 'DZA', 'cn': '阿尔及利亚', 'en': 'Algeria'},
    {'code': 'AND', 'cn': '安道尔', 'en': 'Andorra'},
    {'code': 'AGO', 'cn': '安哥拉', 'en': 'Angola'},
    {'code': 'AIA', 'cn': '安圭拉', 'en': 'Anguilla'},
    {'code': 'ATG', 'cn': '安提瓜和巴布达', 'en': 'Antigua and Barbuda'},
    {'code': 'ARG', 'cn': '阿根廷', 'en': 'Argentina'},
    {'code': 'ARM', 'cn': '亚美尼亚', 'en': 'Armenia'},
    {'code': 'ABW', 'cn': '阿鲁巴', 'en': 'Aruba'},
    {'code': 'AUS', 'cn': '澳大利亚', 'en': 'Australia'},
    {'code': 'AUT', 'cn': '奥地利', 'en': 'Austria'},
    {'code': 'AZE', 'cn': '阿塞拜疆', 'en': 'Azerbaijan'},
    {'code': 'BHS', 'cn': '巴哈马', 'en': 'Bahamas'},
    {'code': 'BHR', 'cn': '巴林', 'en': 'Bahrain'},
    {'code': 'BGD', 'cn': '孟加拉国', 'en': 'Bangladesh'},
    {'code': 'BRB', 'cn': '巴巴多斯', 'en': 'Barbados'},
    {'code': 'BLR', 'cn': '白俄罗斯', 'en': 'Belarus'},
    {'code': 'BEL', 'cn': '比利时', 'en': 'Belgium'},
    {'code': 'BLZ', 'cn': '伯利兹', 'en': 'Belize'},
    {'code': 'BEN', 'cn': '贝宁', 'en': 'Benin'},
    {'code': 'BMU', 'cn': '百慕大', 'en': 'Bermuda'},
    {'code': 'BTN', 'cn': '不丹', 'en': 'Bhutan'},
    {'code': 'BOL', 'cn': '玻利维亚', 'en': 'Bolivia'},
    {'code': 'BIH', 'cn': '波斯尼亚和黑塞哥维那', 'en': 'Bosnia and Herzegovina'},
    {'code': 'BWA', 'cn': '博茨瓦纳', 'en': 'Botswana'},
    {'code': 'BRA', 'cn': '巴西', 'en': 'Brazil'},
    {'code': 'IOT', 'cn': '英属印度洋领地', 'en': 'British Indian Ocean Territory'},
    {'code': 'BRN', 'cn': '文莱', 'en': 'Brunei'},
    {'code': 'BGR', 'cn': '保加利亚', 'en': 'Bulgaria'},
    {'code': 'BFA', 'cn': '布基纳法索', 'en': 'Burkina Faso'},
    {'code': 'BDI', 'cn': '布隆迪', 'en': 'Burundi'},
    {'code': 'KHM', 'cn': '柬埔寨', 'en': 'Cambodia'},
    {'code': 'CMR', 'cn': '喀麦隆', 'en': 'Cameroon'},
    {'code': 'CAN', 'cn': '加拿大', 'en': 'Canada'},
    {'code': 'CPV', 'cn': '佛得角', 'en': 'Cape Verde'},
    {'code': 'CYM', 'cn': '开曼群岛', 'en': 'Cayman Islands'},
    {'code': 'CAF', 'cn': '中非共和国', 'en': 'Central African Republic'},
    {'code': 'TCD', 'cn': '乍得', 'en': 'Chad'},
    {'code': 'CHL', 'cn': '智利', 'en': 'Chile'},
    {'code': 'CHN', 'cn': '中国', 'en': 'China'},
    {'code': 'COL', 'cn': '哥伦比亚', 'en': 'Colombia'},
    {'code': 'COM', 'cn': '科摩罗', 'en': 'Comoros'},
    {'code': 'COG', 'cn': '刚果', 'en': 'Congo'},
    {'code': 'COD', 'cn': '刚果民主共和国', 'en': 'Congo (Democratic Republic)'},
    {'code': 'COK', 'cn': '库克群岛', 'en': 'Cook Islands'},
    {'code': 'CRI', 'cn': '哥斯达黎加', 'en': 'Costa Rica'},
    {'code': 'CIV', 'cn': '科特迪瓦', 'en': "Cote d'Ivoire"},
    {'code': 'HRV', 'cn': '克罗地亚', 'en': 'Croatia'},
    {'code': 'CUB', 'cn': '古巴', 'en': 'Cuba'},
    {'code': 'CYP', 'cn': '塞浦路斯', 'en': 'Cyprus'},
    {'code': 'CZE', 'cn': '捷克', 'en': 'Czech Republic'},
    {'code': 'DNK', 'cn': '丹麦', 'en': 'Denmark'},
    {'code': 'DJI', 'cn': '吉布提', 'en': 'Djibouti'},
    {'code': 'DMA', 'cn': '多米尼克', 'en': 'Dominica'},
    {'code': 'DOM', 'cn': '多米尼加共和国', 'en': 'Dominican Republic'},
    {'code': 'ECU', 'cn': '厄瓜多尔', 'en': 'Ecuador'},
    {'code': 'EGY', 'cn': '埃及', 'en': 'Egypt'},
    {'code': 'SLV', 'cn': '萨尔瓦多', 'en': 'El Salvador'},
    {'code': 'GNQ', 'cn': '赤道几内亚', 'en': 'Equatorial Guinea'},
    {'code': 'ERI', 'cn': '厄立特里亚', 'en': 'Eritrea'},
    {'code': 'EST', 'cn': '爱沙尼亚', 'en': 'Estonia'},
    {'code': 'ETH', 'cn': '埃塞俄比亚', 'en': 'Ethiopia'},
    {'code': 'FLK', 'cn': '福克兰群岛', 'en': 'Falkland Islands'},
    {'code': 'FRO', 'cn': '法罗群岛', 'en': 'Faroe Islands'},
    {'code': 'FJI', 'cn': '斐济', 'en': 'Fiji'},
    {'code': 'FIN', 'cn': '芬兰', 'en': 'Finland'},
    {'code': 'FRA', 'cn': '法国', 'en': 'France'},
    {'code': 'GUF', 'cn': '法属圭亚那', 'en': 'French Guiana'},
    {'code': 'PYF', 'cn': '法属波利尼西亚', 'en': 'French Polynesia'},
    {'code': 'GAB', 'cn': '加蓬', 'en': 'Gabon'},
    {'code': 'GMB', 'cn': '冈比亚', 'en': 'Gambia'},
    {'code': 'GEO', 'cn': '格鲁吉亚', 'en': 'Georgia'},
    {'code': 'DEU', 'cn': '德国', 'en': 'Germany'},
    {'code': 'GHA', 'cn': '加纳', 'en': 'Ghana'},
    {'code': 'GIB', 'cn': '直布罗陀', 'en': 'Gibraltar'},
    {'code': 'GRC', 'cn': '希腊', 'en': 'Greece'},
    {'code': 'GRL', 'cn': '格陵兰', 'en': 'Greenland'},
    {'code': 'GRD', 'cn': '格林纳达', 'en': 'Grenada'},
    {'code': 'GLP', 'cn': '瓜德罗普', 'en': 'Guadeloupe'},
    {'code': 'GUM', 'cn': '关岛', 'en': 'Guam'},
    {'code': 'GTM', 'cn': '危地马拉', 'en': 'Guatemala'},
    {'code': 'GGY', 'cn': '根西岛', 'en': 'Guernsey'},
    {'code': 'GIN', 'cn': '几内亚', 'en': 'Guinea'},
    {'code': 'GNB', 'cn': '几内亚比绍', 'en': 'Guinea-Bissau'},
    {'code': 'GUY', 'cn': '圭亚那', 'en': 'Guyana'},
    {'code': 'HTI', 'cn': '海地', 'en': 'Haiti'},
    {'code': 'HND', 'cn': '洪都拉斯', 'en': 'Honduras'},
    {'code': 'HKG', 'cn': '中国香港', 'en': 'Hong Kong'},
    {'code': 'HUN', 'cn': '匈牙利', 'en': 'Hungary'},
    {'code': 'ISL', 'cn': '冰岛', 'en': 'Iceland'},
    {'code': 'IND', 'cn': '印度', 'en': 'India'},
    {'code': 'IDN', 'cn': '印度尼西亚', 'en': 'Indonesia'},
    {'code': 'IRN', 'cn': '伊朗', 'en': 'Iran'},
    {'code': 'IRQ', 'cn': '伊拉克', 'en': 'Iraq'},
    {'code': 'IRL', 'cn': '爱尔兰', 'en': 'Ireland'},
    {'code': 'IMN', 'cn': '马恩岛', 'en': 'Isle of Man'},
    {'code': 'ISR', 'cn': '以色列', 'en': 'Israel'},
    {'code': 'ITA', 'cn': '意大利', 'en': 'Italy'},
    {'code': 'JAM', 'cn': '牙买加', 'en': 'Jamaica'},
    {'code': 'JPN', 'cn': '日本', 'en': 'Japan'},
    {'code': 'JEY', 'cn': '泽西岛', 'en': 'Jersey'},
    {'code': 'JOR', 'cn': '约旦', 'en': 'Jordan'},
    {'code': 'KAZ', 'cn': '哈萨克斯坦', 'en': 'Kazakhstan'},
    {'code': 'KEN', 'cn': '肯尼亚', 'en': 'Kenya'},
    {'code': 'KIR', 'cn': '基里巴斯', 'en': 'Kiribati'},
    {'code': 'PRK', 'cn': '朝鲜', 'en': "Korea (North)"},
    {'code': 'KOR', 'cn': '韩国', 'en': "Korea (South)"},
    {'code': 'KWT', 'cn': '科威特', 'en': 'Kuwait'},
    {'code': 'KGZ', 'cn': '吉尔吉斯斯坦', 'en': 'Kyrgyzstan'},
    {'code': 'LAO', 'cn': '老挝', 'en': 'Laos'},
    {'code': 'LVA', 'cn': '拉脱维亚', 'en': 'Latvia'},
    {'code': 'LBN', 'cn': '黎巴嫩', 'en': 'Lebanon'},
    {'code': 'LSO', 'cn': '莱索托', 'en': 'Lesotho'},
    {'code': 'LBR', 'cn': '利比里亚', 'en': 'Liberia'},
    {'code': 'LBY', 'cn': '利比亚', 'en': 'Libya'},
    {'code': 'LIE', 'cn': '列支敦士登', 'en': 'Liechtenstein'},
    {'code': 'LTU', 'cn': '立陶宛', 'en': 'Lithuania'},
    {'code': 'LUX', 'cn': '卢森堡', 'en': 'Luxembourg'},
    {'code': 'MAC', 'cn': '中国澳门', 'en': 'Macau'},
    {'code': 'MKD', 'cn': '马其顿', 'en': 'Macedonia'},
    {'code': 'MDG', 'cn': '马达加斯加', 'en': 'Madagascar'},
    {'code': 'MWI', 'cn': '马拉维', 'en': 'Malawi'},
    {'code': 'MYS', 'cn': '马来西亚', 'en': 'Malaysia'},
    {'code': 'MDV', 'cn': '马尔代夫', 'en': 'Maldives'},
    {'code': 'MLI', 'cn': '马里', 'en': 'Mali'},
    {'code': 'MLT', 'cn': '马耳他', 'en': 'Malta'},
    {'code': 'MHL', 'cn': '马绍尔群岛', 'en': 'Marshall Islands'},
    {'code': 'MTQ', 'cn': '马提尼克', 'en': 'Martinique'},
    {'code': 'MRT', 'cn': '毛里塔尼亚', 'en': 'Mauritania'},
    {'code': 'MUS', 'cn': '毛里求斯', 'en': 'Mauritius'},
    {'code': 'MYT', 'cn': '马约特', 'en': 'Mayotte'},
    {'code': 'MEX', 'cn': '墨西哥', 'en': 'Mexico'},
    {'code': 'FSM', 'cn': '密克罗尼西亚', 'en': 'Micronesia'},
    {'code': 'MDA', 'cn': '摩尔多瓦', 'en': 'Moldova'},
    {'code': 'MCO', 'cn': '摩纳哥', 'en': 'Monaco'},
    {'code': 'MNG', 'cn': '蒙古', 'en': 'Mongolia'},
    {'code': 'MNE', 'cn': '黑山', 'en': 'Montenegro'},
    {'code': 'MSR', 'cn': '蒙特塞拉特', 'en': 'Montserrat'},
    {'code': 'MAR', 'cn': '摩洛哥', 'en': 'Morocco'},
    {'code': 'MOZ', 'cn': '莫桑比克', 'en': 'Mozambique'},
    {'code': 'MMR', 'cn': '缅甸', 'en': 'Myanmar'},
    {'code': 'NAM', 'cn': '纳米比亚', 'en': 'Namibia'},
    {'code': 'NRU', 'cn': '瑙鲁', 'en': 'Nauru'},
    {'code': 'NPL', 'cn': '尼泊尔', 'en': 'Nepal'},
    {'code': 'NLD', 'cn': '荷兰', 'en': 'Netherlands'},
    {'code': 'NCL', 'cn': '新喀里多尼亚', 'en': 'New Caledonia'},
    {'code': 'NZL', 'cn': '新西兰', 'en': 'New Zealand'},
    {'code': 'NIC', 'cn': '尼加拉瓜', 'en': 'Nicaragua'},
    {'code': 'NER', 'cn': '尼日尔', 'en': 'Niger'},
    {'code': 'NGA', 'cn': '尼日利亚', 'en': 'Nigeria'},
    {'code': 'NIU', 'cn': '纽埃', 'en': 'Niue'},
    {'code': 'NFK', 'cn': '诺福克岛', 'en': 'Norfolk Island'},
    {'code': 'NOR', 'cn': '挪威', 'en': 'Norway'},
    {'code': 'OMN', 'cn': '阿曼', 'en': 'Oman'},
    {'code': 'PAK', 'cn': '巴基斯坦', 'en': 'Pakistan'},
    {'code': 'PLW', 'cn': '帕劳', 'en': 'Palau'},
    {'code': 'PAN', 'cn': '巴拿马', 'en': 'Panama'},
    {'code': 'PNG', 'cn': '巴布亚新几内亚', 'en': 'Papua New Guinea'},
    {'code': 'PRY', 'cn': '巴拉圭', 'en': 'Paraguay'},
    {'code': 'PER', 'cn': '秘鲁', 'en': 'Peru'},
    {'code': 'PHL', 'cn': '菲律宾', 'en': 'Philippines'},
    {'code': 'POL', 'cn': '波兰', 'en': 'Poland'},
    {'code': 'PRT', 'cn': '葡萄牙', 'en': 'Portugal'},
    {'code': 'PRI', 'cn': '波多黎各', 'en': 'Puerto Rico'},
    {'code': 'QAT', 'cn': '卡塔尔', 'en': 'Qatar'},
    {'code': 'REU', 'cn': '留尼汪', 'en': 'Reunion'},
    {'code': 'ROU', 'cn': '罗马尼亚', 'en': 'Romania'},
    {'code': 'RUS', 'cn': '俄罗斯', 'en': 'Russia'},
    {'code': 'RWA', 'cn': '卢旺达', 'en': 'Rwanda'},
    {'code': 'WSM', 'cn': '萨摩亚', 'en': 'Samoa'},
    {'code': 'SMR', 'cn': '圣马力诺', 'en': 'San Marino'},
    {'code': 'STP', 'cn': '圣多美和普林西比', 'en': 'Sao Tome and Principe'},
    {'code': 'SAU', 'cn': '沙特阿拉伯', 'en': 'Saudi Arabia'},
    {'code': 'SEN', 'cn': '塞内加尔', 'en': 'Senegal'},
    {'code': 'SRB', 'cn': '塞尔维亚', 'en': 'Serbia'},
    {'code': 'SYC', 'cn': '塞舌尔', 'en': 'Seychelles'},
    {'code': 'SLE', 'cn': '塞拉利昂', 'en': 'Sierra Leone'},
    {'code': 'SGP', 'cn': '新加坡', 'en': 'Singapore'},
    {'code': 'SXM', 'cn': '圣马丁', 'en': 'Sint Maarten'},
    {'code': 'SVK', 'cn': '斯洛伐克', 'en': 'Slovakia'},
    {'code': 'SVN', 'cn': '斯洛文尼亚', 'en': 'Slovenia'},
    {'code': 'SLB', 'cn': '所罗门群岛', 'en': 'Solomon Islands'},
    {'code': 'SOM', 'cn': '索马里', 'en': 'Somalia'},
    {'code': 'ZAF', 'cn': '南非', 'en': 'South Africa'},
    {'code': 'SSD', 'cn': '南苏丹', 'en': 'South Sudan'},
    {'code': 'ESP', 'cn': '西班牙', 'en': 'Spain'},
    {'code': 'LKA', 'cn': '斯里兰卡', 'en': 'Sri Lanka'},
    {'code': 'SDN', 'cn': '苏丹', 'en': 'Sudan'},
    {'code': 'SUR', 'cn': '苏里南', 'en': 'Suriname'},
    {'code': 'SWZ', 'cn': '斯威士兰', 'en': 'Swaziland'},
    {'code': 'SWE', 'cn': '瑞典', 'en': 'Sweden'},
    {'code': 'CHE', 'cn': '瑞士', 'en': 'Switzerland'},
    {'code': 'SYR', 'cn': '叙利亚', 'en': 'Syria'},
    {'code': 'TWN', 'cn': '中国台湾', 'en': 'Taiwan'},
    {'code': 'TJK', 'cn': '塔吉克斯坦', 'en': 'Tajikistan'},
    {'code': 'TZA', 'cn': '坦桑尼亚', 'en': 'Tanzania'},
    {'code': 'THA', 'cn': '泰国', 'en': 'Thailand'},
    {'code': 'TLS', 'cn': '东帝汶', 'en': 'Timor-Leste'},
    {'code': 'TGO', 'cn': '多哥', 'en': 'Togo'},
    {'code': 'TKL', 'cn': '托克劳', 'en': 'Tokelau'},
    {'code': 'TON', 'cn': '汤加', 'en': 'Tonga'},
    {'code': 'TTO', 'cn': '特立尼达和多巴哥', 'en': 'Trinidad and Tobago'},
    {'code': 'TUN', 'cn': '突尼斯', 'en': 'Tunisia'},
    {'code': 'TUR', 'cn': '土耳其', 'en': 'Turkey'},
    {'code': 'TKM', 'cn': '土库曼斯坦', 'en': 'Turkmenistan'},
    {'code': 'TCA', 'cn': '特克斯和凯科斯群岛', 'en': 'Turks and Caicos Islands'},
    {'code': 'TUV', 'cn': '图瓦卢', 'en': 'Tuvalu'},
    {'code': 'UGA', 'cn': '乌干达', 'en': 'Uganda'},
    {'code': 'UKR', 'cn': '乌克兰', 'en': 'Ukraine'},
    {'code': 'ARE', 'cn': '阿联酋', 'en': 'United Arab Emirates'},
    {'code': 'GBR', 'cn': '英国', 'en': 'United Kingdom'},
    {'code': 'USA', 'cn': '美国', 'en': 'United States'},
    {'code': 'URY', 'cn': '乌拉圭', 'en': 'Uruguay'},
    {'code': 'UZB', 'cn': '乌兹别克斯坦', 'en': 'Uzbekistan'},
    {'code': 'VUT', 'cn': '瓦努阿图', 'en': 'Vanuatu'},
    {'code': 'VAT', 'cn': '梵蒂冈', 'en': 'Vatican City'},
    {'code': 'VEN', 'cn': '委内瑞拉', 'en': 'Venezuela'},
    {'code': 'VNM', 'cn': '越南', 'en': 'Vietnam'},
    {'code': 'WLF', 'cn': '瓦利斯和富图纳', 'en': 'Wallis and Futuna'},
    {'code': 'YEM', 'cn': '也门', 'en': 'Yemen'},
    {'code': 'ZMB', 'cn': '赞比亚', 'en': 'Zambia'},
    {'code': 'ZWE', 'cn': '津巴布韦', 'en': 'Zimbabwe'}
]